### ISSUE TITLE
无法新建Md模板

### ISSUE THREAD

**Issue by yuedingwangji** [kairyou/SublimeTmpl#22]
你好，我在C:\Users\yuedingwagnji\AppData\Roaming\Sublime Text 3\Packages\User\SublimeTmpl\templates
这里添加了一个 md模板，然后修改了key-binder 我是参照这个的http://blog.jobbole.com/96993/ ，这4个文件我都改了，可还是不行，控制台报错如下：
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 812, in run_
return self.run(edit, **args)
File "C:\Users\yuedingwagnji\AppData\Roaming\Sublime Text 3\Packages\SublimeTmpl\sublime-tmpl.py", line 36, in run
tmpl = self.get_code(type)
File "C:\Users\yuedingwagnji\AppData\Roaming\Sublime Text 3\Packages\SublimeTmpl\sublime-tmpl.py", line 89, in get_code
code = sublime.load_resource(self.tmpl_path)
File "C:\Program Files\Sublime Text 3\sublime.py", line 190, in load_resource
s = sublime_api.load_resource(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 71: invalid start byte

**Comment by kairyou** [comment]
你好, 看起来是 你的md.tmpl 文件里面字符解析问题, 估计不是utf-8编码, 你可以编辑`md.tmpl`, 然后另存为utf-8编码, 然后试试

**Comment by yuedingwangji** [comment]
还真是如此..
