### ISSUE TITLE
TypeError: unsupported operand type(s) for %: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by clawjelly** [kairyou/SublimeTmpl#33]
`
Traceback (most recent call last):
  File "D:\Temp\SublimeTemp\sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "D:\Temp\SublimeTemp\Data\Packages\SublimeTmpl\sublime-tmpl.py", line 111, in run
    tmpl = self.get_code(type)
  File "D:\Temp\SublimeTemp\Data\Packages\SublimeTmpl\sublime-tmpl.py", line 205, in get_code
    return self.format_tag(code)
  File "D:\Temp\SublimeTemp\Data\Packages\SublimeTmpl\sublime-tmpl.py", line 213, in format_tag
    pattern = get_replace_pattern(settings)
  File "D:\Temp\SublimeTemp\Data\Packages\SublimeTmpl\sublime-tmpl.py", line 39, in get_replace_pattern
    x = replace_pattern % "test"
TypeError: unsupported operand type(s) for %: 'NoneType' and 'str'
`

This is what i get when i select File>New File (SublimeTmpl)>python on a fresh install.

**Comment by clawjelly** [comment]
Okay, i guess i thought i restarted Sublime. Didn't. Sorry.
